### ISSUE TITLE
[Question] Can the SDK use with instant messaging?

### ISSUE THREAD

**Issue by anniewey** [nsotelo/react-native-sip#3]
Hi, just wondering can the SDK use with instant messaging? I need VOIP and instant messaging functions.

**Comment by nsotelo** [comment]
I only added support for voice calls because that's what I needed for a project, and I haven't got time to work on other features right now but you're welcome to send a pull-request or fork this for your own purposes.

This library wraps liblinphone which supports instant messages for [java](https://download.linphone.org/releases/docs/liblinphone/latest/java/org/linphone/core/ChatMessage.html) and [swift](https://download.linphone.org/releases/docs/liblinphone/latest/swift/Classes/ChatMessage.html). The wrapping code is [here (ios)](https://github.com/nsotelo/react-native-sip/blob/master/ios/Sip.swift) and [here (kotlin)](https://github.com/nsotelo/react-native-sip/blob/master/android/src/main/java/com/reactnativesip/SipModule.kt), and then the functions defined there are exposed through [src/native-wrapper.ts](https://github.com/nsotelo/react-native-sip/blob/master/src/native-wrapper.ts) which needs to be re-exported from [src/index.ts](https://github.com/nsotelo/react-native-sip/blob/master/src/index.ts).

If you're planning to use this for Android you shouldn't have problems but iOS is a bit tricky, the only way I can get it to build is by manually removing [this code from folly](https://github.com/facebook/folly/blob/b72a70a35ada45ac286eb60028c0ecf5f6725665/folly/portability/Config.h#L19-L21). If you try to compile without removing this xcode will raise an error and indicate exactly where this line is, but at least in my case the app works perfectly without this line. If you can figure out a way to compile without this hack, please let me know!

**Comment by anniewey** [comment]
Thanks for the reply. As I'm not familiar with native codes, these could be pretty difficult for me to implement. Nonetheless, thanks for insight
